<?php
    use CustomGento\Cookiebot\ViewModel\Script as CookiebotScriptViewModel;
    use Magento\Framework\View\Element\Template;
    use Magento\Framework\View\Helper\SecureHtmlRenderer;

    /** @var CookiebotScriptViewModel $viewModel */
    /** @var SecureHtmlRenderer $secureRenderer */
    /** @var Template $block */

    $viewModel = $block->getData('view_model')
?>
<?= /* @noEscape */ $viewModel->getScript() ?>
<?php

if ($viewModel->isGoogleConsentModeEnabled()) {
    $scriptString = '
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag("consent", "default", {
            ad_personalization: "denied",
            ad_storage: "denied",
            ad_user_data: "denied",
            analytics_storage: "denied",
            functionality_storage: "denied",
            personalization_storage: "denied",
            security_storage: "granted",
            wait_for_update: 500,
        });
        gtag("set", "ads_data_redaction", true);
        gtag("set", "url_passthrough", true);
    ';

    // checking on if SecureHtmlRenderer exists first, because this module is still compatible with Magento 2.3.x which doesn't include this class
    if (class_exists(SecureHtmlRenderer::class)) {
        echo $secureRenderer->renderTag('script', ['data-cookieconsent' => 'ignore'], $scriptString, false);
    } else {
        echo '<script data-cookieconsent="ignore">' . $scriptString . '<script>';
    }
}
