<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<?php /** @var CustomGento\Cookiebot\ViewModel\Script $viewModel */ ?>
<?php $viewModel = $block->getData('view_model') ?>
<?= /* @noEscape */ $viewModel->getScript() ?>

<?php
if ($viewModel->googleConsentIsEnabled()):
    ?>
    <script data-cookieconsent="ignore">
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag("consent", "default", {
            ad_personalization: "denied",
            ad_storage: "denied",
            ad_user_data: "denied",
            analytics_storage: "denied",
            functionality_storage: "denied",
            personalization_storage: "denied",
            security_storage: "granted",
            wait_for_update: 500,
        });
        gtag("set", "ads_data_redaction", true);
        gtag("set", "url_passthrough", true);
    </script>
<?php endif; ?>
